# Generated by Django 4.2.3 on 2023-07-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
