# Generated by Django 4.2.3 on 2023-07-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0002_alter_publications_data_alter_publications_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cod',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminkaDrivers.driver'),
        ),
    ]
