# Generated by Django 4.2.3 on 2023-07-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0003_cod_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminkaDrivers.driver'),
        ),
    ]
