# Generated by Django 4.2.3 on 2023-07-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0004_alter_cod_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cod',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='cod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminkaDrivers.cod'),
        ),
    ]
