# Generated by Django 4.2.3 on 2023-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0005_remove_cod_driver_driver_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='dataOfStartRoute',
            field=models.DateField(default='2020-10-10'),
        ),
        migrations.AddField(
            model_name='publications',
            name='summ',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
