# Generated by Django 4.2.3 on 2023-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0006_publications_dataofstartroute_publications_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='dataOfStartRoute',
            field=models.DateField(default='2020.10.20'),
        ),
    ]
