# Generated by Django 4.2.3 on 2023-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0008_alter_publications_dataofstartroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegramId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
