# Generated by Django 4.2.3 on 2023-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0009_driver_telegramid'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='allowed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
