# Generated by Django 4.2.3 on 2023-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0010_publications_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='PublicationsAllowed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
