# Generated by Django 4.2.3 on 2023-07-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0011_publications_publicationsallowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name_plural': 'Drivers Publications'},
        ),
        migrations.AlterField(
            model_name='publications',
            name='PublicationsAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
