# Generated by Django 4.2.3 on 2023-07-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminkaDrivers', '0012_alter_publications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cod',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='adminkaDrivers.cod'),
        ),
    ]
